### ISSUE TITLE
Counting Shrooms - Level 2: North Cavern

### ISSUE THREAD

**Issue by Awetizmo** [Jaysyn904/RATDOG#10]
![image](https://user-images.githubusercontent.com/107700980/174357580-bdf28249-c7ef-4d43-934c-7880bb6c6fab.png)

**Comment by Awetizmo** [comment]
![image](https://user-images.githubusercontent.com/107700980/174398503-2818d9ad-e175-4fc1-851a-d98b06f63bc5.png)

Also this is being spammed on entrance.

**Comment by Ysengwen** [comment]
The mushrooms still count down.

**Comment by Jaysyn904** [comment]
This should be fixed with the next nwsync.
