### ISSUE TITLE
Forest of Hope: North - Spawn/Corpse Issue [NESS]

### ISSUE THREAD

**Issue by Awetizmo** [Jaysyn904/RATDOG#12]
Before spawning, code is thrown into the Data Window.
![image](https://user-images.githubusercontent.com/107700980/174478961-3bfc7a32-8527-4cf2-874b-ffb5479d13bf.png)

Monsters in the region turn into empty corpses.

https://user-images.githubusercontent.com/107700980/174478976-84bc777a-1f83-4c3a-a1f6-1c66a2e2fe75.mp4

**Comment by Jaysyn904** [comment]
Not seeing a bug here.  Both of these things are normal & expected.  The text is debug text & will be removed eventually.
