### ISSUE TITLE
The Spiders Captive Quest 

### ISSUE THREAD

**Issue by Awetizmo** [Jaysyn904/RATDOG#14]
![image](https://user-images.githubusercontent.com/107700980/174602130-952a6de6-3be1-486f-ae72-04396ed6d986.png)

Took the quest fine, saved the father- as soon as father was saved, quest log updated to what is in the image. Went back to Daughter who says father was never saved.

**Comment by Jaysyn904** [comment]
This _**should**_ be fixed now.
